//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMining.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class APILogin
    {
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string active { get; set; }
        public string Organization { get; set; }
        public string UserRole { get; set; }
        public string OrgKRAPIN { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string PhysicalAddress { get; set; }
    }
}
