//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMining.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyDataEntities : DbContext
    {
        public MyDataEntities()
            : base("name=MyDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person_IDs> Person_IDs { get; set; }
        public virtual DbSet<APILogin> APILogins { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<STATIC_REGISTER_QUESTION> STATIC_REGISTER_QUESTION { get; set; }
        public virtual DbSet<UserRoleAssignment> UserRoleAssignments { get; set; }
        public virtual DbSet<APIUsage> APIUsages { get; set; }
        public virtual DbSet<STATIC_DATA_USE_REASON> STATIC_DATA_USE_REASON { get; set; }
        public virtual DbSet<vw_OrganizationInfo> vw_OrganizationInfo { get; set; }
        public virtual DbSet<Person_Search_Log> Person_Search_Log { get; set; }
        public virtual DbSet<vw_Applications> vw_Applications { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Person_Tmp> Person_Tmp { get; set; }
    
        public virtual ObjectResult<proc_GetDailySummaries_Result> proc_GetDailySummaries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetDailySummaries_Result>("proc_GetDailySummaries");
        }
    
        public virtual ObjectResult<proc_GetDailySummariesForHomepage_Result> proc_GetDailySummariesForHomepage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetDailySummariesForHomepage_Result>("proc_GetDailySummariesForHomepage");
        }
    
        public virtual ObjectResult<proc_GetDailySummariesPerUser_Result> proc_GetDailySummariesPerUser(string muser)
        {
            var muserParameter = muser != null ?
                new ObjectParameter("muser", muser) :
                new ObjectParameter("muser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetDailySummariesPerUser_Result>("proc_GetDailySummariesPerUser", muserParameter);
        }
    
        public virtual ObjectResult<proc_GetSummaryResources_Result> proc_GetSummaryResources()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetSummaryResources_Result>("proc_GetSummaryResources");
        }
    }
}
