//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMining.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_IDs
    {
        public string ID_Number { get; set; }
        public string KRAPIN { get; set; }
        public string MobilePhone { get; set; }
        public string NHIF { get; set; }
        public string NSSF { get; set; }
        public string PASSPORT { get; set; }
        public Nullable<bool> Processed { get; set; }
    }
}
