//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMining.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Tmp
    {
        public string ID_Number { get; set; }
        public string Surname { get; set; }
        public string First_Name { get; set; }
        public string Other_Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Citizenship { get; set; }
        public string Clan { get; set; }
        public string Ethnic_Group { get; set; }
        public string Family { get; set; }
        public string Serial_Number { get; set; }
        public string Place_of_Birth { get; set; }
        public string Place_of_Live { get; set; }
        public int id { get; set; }
        public Nullable<bool> Processed { get; set; }
    }
}
