//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMining.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Search_Log
    {
        public int id { get; set; }
        public string username { get; set; }
        public string ID_Number { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Found { get; set; }
    }
}
